"""Google Gemini LLM provider implementation with error handling and fallback."""
import json
import logging
from typing import Optional
import httpx
from app.config import settings
from app.providers.base import BaseLLMProvider

logger = logging.getLogger(__name__)


class GeminiProvider(BaseLLMProvider):
    """Google Gemini API provider using async REST."""

    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        self.model = settings.GEMINI_MODEL or "gemini-1.5-flash"

    def get_provider_name(self) -> str:
        return "gemini"

    def is_mock(self) -> bool:
        return False

    async def generate(self, prompt: str, system_prompt: Optional[str] = None,
                       max_tokens: int = 2000, temperature: float = 0.3) -> str:
        """Generate text completion from Google Gemini."""
        if not self.api_key or self.api_key.startswith("your_"):
            logger.warning("Gemini API key missing or placeholder. Falling back to deterministic mock.")
            from app.providers.mock_provider import MockProvider
            return await MockProvider().generate(prompt, system_prompt, max_tokens, temperature)

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        full_prompt = f"{system_prompt}\n\n{prompt}" if system_prompt else prompt

        payload = {
            "contents": [
                {
                    "parts": [
                        {"text": full_prompt}
                    ]
                }
            ],
            "generationConfig": {
                "maxOutputTokens": max_tokens,
                "temperature": temperature,
            }
        }

        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()
                candidates = data.get("candidates", [])
                if candidates and "content" in candidates[0]:
                    parts = candidates[0]["content"].get("parts", [])
                    if parts and "text" in parts[0]:
                        return parts[0]["text"].strip()
                return "No response generated by Gemini."
        except Exception as e:
            logger.error(f"Gemini generation error: {e}. Falling back to mock generator.")
            from app.providers.mock_provider import MockProvider
            return await MockProvider().generate(prompt, system_prompt, max_tokens, temperature)

    async def generate_structured(self, prompt: str, system_prompt: Optional[str] = None,
                                   max_tokens: int = 2000, temperature: float = 0.3) -> dict:
        """Generate structured JSON response from Gemini."""
        effective_system = (system_prompt or "") + "\nYou MUST return valid JSON only."
        raw_text = await self.generate(prompt, effective_system, max_tokens, temperature)
        try:
            cleaned = raw_text.strip()
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            if cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            return json.loads(cleaned.strip())
        except Exception:
            return {"raw_response": raw_text, "status": "unstructured"}
